# 一、Series
## 1.Series的创建

In [9]:
import pandas as pd
s = pd.Series([10,2,3,4,5])
print(s) #左边索引，右边数据
#自定义索引
s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'])
#定义name
s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'],name  = '月份')
print(s)

0    10
1     2
2     3
3     4
4     5
dtype: int64
a    10
b     2
c     3
d     4
e     5
Name: 月份, dtype: int64

In [10]:
# 通过字典来创建
s = pd.Series({'a':10,'b':2,'c':3,'d':4})
print(s)
s1 = pd.Series(s,index = ['a','d']) # 可以只取出一部分，“s“必须要是Series
print(s1)

a    10
b     2
c     3
d     4
dtype: int64
a    10
d     4
dtype: int64

## 2.Series的属性

In [25]:
print(s)
print(s.index)
print(s.values)
print(s.shape,s.ndim,s.size)
print(s.dtype)
s.name = "test"
print(s.name)
print(s.loc['a']) #显式索引，用自定义的index获取
print(s.loc['a':'c']) #支持切片
print(s.iloc[0:2]) #隐式索引，用默认的index获取
print(s.at['a'])
print(s.iat[0]) # at 和 iat 都不支持切片

a    10
b     2
c     3
d     4
Name: test, dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='str')
[10  2  3  4]
(4,) 1 4
int64
test
10
a    10
b     2
c     3
Name: test, dtype: int64
a    10
b     2
Name: test, dtype: int64
10
10

## 3.访问数据

In [47]:
import pandas as pd
s = pd.Series([4,2,3,1,5])
print(s[0])
s = pd.Series([4,2,3,1,5],index=['a','b','c','d','e'])
print(s['a'])
#print(s[0]) # 如果有用自定义标签的话，不能通过默认标签的索引访问数据
print(s[s<3]) #布尔索引，中括号里写对value的布尔表达式
s['f'] = 6 #可以随时加一个，跟字典一样
print(s.head()) # 默认打印前五行
print(s.head(2)) #前两行
print(s.tail()) # 默认打印后五行
print(s.tail(3)) #后三行

4
4
b    2
d    1
dtype: int64
a    4
b    2
c    3
d    1
e    5
dtype: int64
a    4
b    2
dtype: int64
b    2
c    3
d    1
e    5
f    6
dtype: int64
d    1
e    5
f    6
dtype: int64

## 4.常见函数

In [50]:
import numpy as np
s = pd.Series([10,2,np.nan,None,4,5],index=['a','b','c','d','e','f'])
print(s)

a    10.0
b     2.0
c     NaN
d     NaN
e     4.0
f     5.0
dtype: float64

In [55]:
s.head(3)
s.tail(2)

e    4.0
f    5.0
dtype: float64

In [56]:
# 查看所有的描述性信息
s.describe()
# count : 统计个数（忽略缺失值）

count     4.00000
mean      5.25000
std       3.40343
min       2.00000
25%       3.50000
50%       4.50000
75%       6.25000
max      10.00000
dtype: float64

In [57]:
# 获取元素个数
s.count()

np.int64(4)

In [62]:
# 获取元素索引
print(s.keys()) # 方法
print(s.index) # 属性

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')

In [63]:
# 判断缺失值
print(s.isna())

a    False
b    False
c     True
d     True
e    False
f    False
dtype: bool

In [66]:
# 判断是否在另一个集合里
s.isin([4,5])

a    False
b    False
c    False
d    False
e     True
f     True
dtype: bool

In [81]:
#
print(s.mean())
print(s.sum())
print(s.std()) # 标准差
print(s.var()) # 方差
print(s.min())
print(s.max())
print(s.sort_values()) # 按值的大小排序
print(s.median()) # 中位数
print(s.quantile(q=[0.25,0.5,0.75])) #分位数
s['g'] = 4
print(s.mode()) #众数

5.0
25.0
3.0
9.0
2.0
10.0
b     2.0
e     4.0
g     4.0
f     5.0
a    10.0
c     NaN
d     NaN
dtype: float64
4.0
0.25    4.0
0.50    4.0
0.75    5.0
dtype: float64
0    4.0
dtype: float64

In [82]:
print(s.value_counts()) # 每个元素的计数

4.0     2
10.0    1
2.0     1
5.0     1
Name: count, dtype: int64

In [86]:
# 去重
s.drop_duplicates()

a    10.0
b     2.0
c     NaN
e     4.0
f     5.0
dtype: float64

In [101]:
s.unique() # 返回一个列表

array([10.,  2., nan,  4.,  5.])

In [90]:
s.nunique() # 返回去重后的元素个数

4

In [92]:
# 排序
s.sort_index() # 按索引排序

a    10.0
b     2.0
c     NaN
d     NaN
e     4.0
f     5.0
g     4.0
dtype: float64

In [98]:
s.sort_values() #按值排序

b     2.0
e     4.0
g     4.0
f     5.0
a    10.0
c     NaN
d     NaN
dtype: float64

# 二、DataFrame

## 1.dataframe 的创建方式

In [213]:
import pandas as pd
import numpy as np

# 通过Series来创建
s1 =pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s2 =pd.Series([6,7,8,9,10]) # 因为s2中没有index为abcde的值，所以dataframe里面s2的值全部都是缺失值
df = pd.DataFrame({"第一列":s1,"第二列":s2})
print(df)

# 通过字典来创建
df = pd.DataFrame({
    "id":[1,2,3,4,5],
    "name":["a","b","c","d","e"],
    "age":[20,20,30,40,50]
},index = ['a','b','c','d','e'],columns = ['name','age']) # 可以调整参数的顺序，也可以只获取部分参数
print(df)

   第一列   第二列
a  1.0   NaN
b  2.0   NaN
c  3.0   NaN
d  4.0   NaN
e  5.0   NaN
0  NaN   6.0
1  NaN   7.0
2  NaN   8.0
3  NaN   9.0
4  NaN  10.0
  name  age
a    a   20
b    b   20
c    c   30
d    d   40
e    e   50

## 2.dataframe的属性

In [114]:
print('行索引：')
print(df.index)
print('列标签：')
print(df.columns)

行索引：
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
列标签：
Index(['name', 'age'], dtype='str')

In [115]:
print('值：')
print(df.values) # 返回一个矩阵

值：
[['a' 10]
 ['b' 20]
 ['c' 30]
 ['d' 40]
 ['e' 50]]

In [120]:
print('维度：',df.ndim)
print('形状',df.shape)
print('元素个数',df.size)
print('数据类型：',df.dtypes)

维度： 2
形状 (5, 2)
元素个数 10
数据类型： name      str
age     int64
dtype: object

In [129]:
print('行列转置：')
#print(df.T)
print(df.T.columns) # 行索引和列标签也进行了变化

行列转置：
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [136]:
# 获取元素 loc iloc at iat
#获取某行数据
print(df.loc['b'])
print(df.iloc[2])

name     b
age     20
Name: b, dtype: object
name     c
age     30
Name: c, dtype: object

In [139]:
# 获取某列数据
print(df.loc[:,'name'])
print(df.iloc[:,0]) #切片方法

a    a
b    b
c    c
d    d
e    e
Name: name, dtype: str
a    a
b    b
c    c
d    d
e    e
Name: name, dtype: str

In [144]:
# 单个数据
print(df.at['b','name'])
print(df.iat[1,0])
print(df.iloc[1,0])

b
b
b

## 3.获取数据

In [150]:
print(df['name'])
print(df.name)
print(df.loc[:,'name'])

a    a
b    b
c    c
d    d
e    e
Name: name, dtype: str
a    a
b    b
c    c
d    d
e    e
Name: name, dtype: str
a    a
b    b
c    c
d    d
e    e
Name: name, dtype: str

In [152]:
print(df[['name','age']]) #返回值是dataframe，可以获取多列值

  name  age
a    a   10
b    b   20
c    c   30
d    d   40
e    e   50

In [153]:
# 查看部分数据
print(df.head(2))
print(df.tail(2))

  name  age
a    a   10
b    b   20
  name  age
d    d   40
e    e   50

In [160]:
# 布尔索引
df.age>10 # 只能判断

a    False
b     True
c     True
d     True
e     True
Name: age, dtype: bool

In [161]:
df[df.age>10] # 获取全部信息

  name  age
b    b   20
c    c   30
d    d   40
e    e   50

In [163]:
df[(df.age>10) & (df.name>'b')] # 两个条件需要用（）括起来

  name  age
c    c   30
d    d   40
e    e   50

In [167]:
# 随机抽样
df.sample(3) # 随机取多条数据

  name  age
e    e   50
d    d   40
c    c   30

## 4.常用方法

In [202]:
df['score'] = [66,77,68,99,87] # loc 赋值
#df.drop(columns = [2]) # 会保留原来列，只删除数据
#del df[2] # 直接删除该列，完全删除
del df['socre']
df

  name  age  score
a    a   10     66
b    b   20     77
c    c   30     68
d    d   40     99
e    e   50     87

In [175]:
print(df.head(3))
print(df.tail(3))

  name  age   2
a    a   10  66
b    b   20  77
c    c   30  68
  name  age   2
c    c   30  68
d    d   40  99
e    e   50  87

In [193]:
print(df.isin([66,87,'a','c']))

    name    age  socre
a   True  False   True
b  False  False  False
c   True  False  False
d  False  False  False
e  False  False   True

In [194]:
print(df.isna())

    name    age  socre
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False
e  False  False  False

In [206]:
print(df.sum()) # 每一column：字符串拼接，数字相加
print(df['score'].sum())
print(df.score.max())
# .mean()
# .median() 中位数
# .mode()
# .quantile(q) 分位数
# .std() 标准差
# .var() 方差

name     abcde
age        150
score      397
dtype: object
397
99

In [208]:
print(df.describe())

             age      score
count   5.000000   5.000000
mean   30.000000  79.400000
std    15.811388  13.758634
min    10.000000  66.000000
25%    20.000000  68.000000
50%    30.000000  77.000000
75%    40.000000  87.000000
max    50.000000  99.000000

In [210]:
df.count()

name     5
age      5
score    5
dtype: int64

In [215]:
df.value_counts() # 只有完全一样的一行才可以算作两次

name  age
a     20     1
b     20     1
c     30     1
d     40     1
e     50     1
Name: count, dtype: int64

In [217]:
# 去重
# df.drop_duplicates()
# 检查是否是重复的
# df.duplicated()
# 可以指定列查看是否是重复的
df.duplicated(subset='age')

a    False
b     True
c    False
d    False
e    False
dtype: bool

In [218]:
df.sample()

  name  age
e    e   50

In [223]:
df.replace(50,30) # 把所有的50换成30,也可以指定列操作

  name  age
a    a   20
b    b   20
c    c   30
d    d   40
e    e   30

In [226]:
# 累计和累计积
df.cumsum() #可以用参数axis改变按行按列：0-->按列 ； 1-->按行
df.cummin() #累计出现的最小的，和df.max()效果一样

  name  age
a    a   20
b    a   20
c    a   20
d    a   20
e    a   20

In [228]:
# 排序
# 按索引排序
print(df.sort_index()) #默认从低到高排序
print(df.sort_index(ascending=False)) #可改变参数为降序排列

  name  age
a    a   20
b    b   20
c    c   30
d    d   40
e    e   50
  name  age
e    e   50
d    d   40
c    c   30
b    b   20
a    a   20

In [232]:
# 按值排序
print(df.sort_values(by='age')) # 参数by= ， 按照什么排序
print(df.sort_values(by=['age','name'], ascending=[True,False])) # 可以设置多个参照，并且每个都可以独立设置升序和降序

  name  age
a    a   20
b    b   20
c    c   30
d    d   40
e    e   50
  name  age
b    b   20
a    a   20
c    c   30
d    d   40
e    e   50

In [243]:
# 取最大的两个
df.nlargest(2,columns = 'age') # 同样可以写多列 ： columns = ['age','name','score'],也可以改升序降序

  name  age
e    e   50
d    d   40

In [244]:
# 取最小的两个
df.nsmallest(2,columns = 'age')

  name  age
a    a   20
b    b   20