# 数据分析
## 1.数据的导入与导出

In [20]:
# 数据的导入
import pandas as pd
df = pd.read_csv("data/student_scores .csv") #导出的格式是dataframe
df
print(df.tail())
print(df.语文.mean())
# 数据的导出
df.to_csv("data/new_student_scores .csv",index=False) # index=False可以让导出的数据不保留原数据的index，避免重复

    Unnamed: 0  姓名      班级    语文    数学    英语  选科
11          11  马丽  高一(2)班  70.0  56.0  58.0  理科
12          12  朱峰  高一(3)班  62.0  85.0  78.0  理科
13          13  胡军  高一(2)班  94.0   NaN  97.0  文科
14          14  林芳  高一(2)班  56.0   NaN  80.0  文科
15          15  郭涛  高一(3)班   NaN  83.0   NaN  理科
81.35714285714286

In [19]:
# json
df = pd.read_json("data/users.json")
#print(df)

import json
with open('data/users.json',encoding = 'utf-8') as f: # encoding = '数据格式' (gbk，utf-8...)
    data = json.load(f)
#print(data)
print(type(data)) # 是列表 'list'
df = pd.DataFrame(data)
print(type(df))
df

<class 'list'>
<class 'pandas.DataFrame'>

,id,用户名,年龄,性别,活跃度,订阅,地址,兴趣,注册日期
0,1,user_01,44,女,0.56,False,"{'国家': '中国', '城市': '成都', '邮编': '858414'}","[科技, 美食, 阅读]",2024-04-16
1,2,user_02,18,男,0.58,True,"{'国家': '中国', '城市': '武汉', '邮编': '461264'}","[运动, 旅行, 科技]",2024-08-15
2,3,user_03,22,女,0.03,False,"{'国家': '中国', '城市': '上海', '邮编': '906325'}","[阅读, 摄影, 音乐]",2024-01-17
3,4,user_04,59,女,0.37,False,"{'国家': '中国', '城市': '武汉', '邮编': '495833'}","[摄影, 科技, 音乐]",2024-09-14
4,5,user_05,60,男,0.65,False,"{'国家': '中国', '城市': '北京', '邮编': '287143'}","[摄影, 旅行, 运动]",2024-01-16
5,6,user_06,32,男,0.76,False,"{'国家': '中国', '城市': '武汉', '邮编': '806215'}","[摄影, 旅行, 美食]",2024-04-23
6,7,user_07,32,男,0.46,True,"{'国家': '中国', '城市': '成都', '邮编': '297636'}","[运动, 科技, 音乐]",2023-03-06
7,8,user_08,57,男,0.24,True,"{'国家': '中国', '城市': '北京', '邮编': '722795'}","[科技, 美食, 旅行]",2023-11-20
8,9,user_09,21,男,0.74,False,"{'国家': '中国', '城市': '武汉', '邮编': '345722'}","[美食, 摄影, 科技]",2022-05-24
9,10,user_10,50,女,0.23,False,"{'国家': '中国', '城市': '西安', '邮编': '726962'}","[音乐, 运动, 阅读]",2024-06-16
10,11,user_11,27,男,0.41,False,"{'国家': '中国', '城市': '北京', '邮编': '683761'}","[阅读, 音乐, 摄影]",2023-03-14
11,12,user_12,53,女,0.05,False,"{'国家': '中国', '城市': '武汉', '邮编': '923975'}","[音乐, 游戏, 美食]",2023-02-23
12,13,user_13,27,女,0.38,False,"{'国家': '中国', '城市': '上海', '邮编': '990598'}","[美食, 阅读, 音乐]",2022-05-28
13,14,user_14,47,男,0.56,False,"{'国家': '中国', '城市': '西安', '邮编': '655736'}","[阅读, 美食, 运动]",2022-09-19
14,15,user_15,31,女,0.65,False,"{'国家': '中国', '城市': '成都', '邮编': '196955'}","[美食, 科技, 阅读]",2023-01-22
15,16,user_16,56,男,0.87,True,"{'国家': '中国', '城市': '西安', '邮编': '859489'}","[美食, 游戏, 运动]",2024-06-09
16,17,user_17,39,女,0.96,True,"{'国家': '中国', '城市': '上海', '邮编': '299254'}","[运动, 音乐, 美食]",2024-07-25
17,18,user_18,33,男,0.40,True,"{'国家': '中国', '城市': '西安', '邮编': '437237'}","[旅行, 美食, 摄影]",2023-07-01
18,19,user_19,59,女,0.31,False,"{'国家': '中国', '城市': '西安', '邮编': '621433'}","[游戏, 科技, 音乐]",2023-04-26
19,20,user_20,38,男,0.37,False,"{'国家': '中国', '城市': '北京', '邮编': '689849'}","[美食, 音乐, 运动]",2022-01-17

## 2.数据处理

In [31]:
# 缺失值的处理
# np.nan：not a number
# None,pd.NA:don't exist 不存在
import pandas as pd
import numpy as np
s = pd.Series([1,2,np.nan,None,pd.NA])
print(s)
df = pd.DataFrame([[1,pd.NA,2],[2,3,4],[np.nan,None,3]])
df
# 查看是否是缺失值
print(s.isna())
print(s.isnull())
print(s.isnull().sum())
print(df.isna())
print(df.isnull())
print(df.isnull().sum()) #.sum 查看每个column的缺失值个数

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
3
       0      1      2
0  False   True  False
1  False  False  False
2   True   True  False
       0      1      2
0  False   True  False
1  False  False  False
2   True   True  False
0    1
1    2
2    0
dtype: int64

In [43]:
# 剔除缺失值
print(s.dropna())
print(df)
print(df.dropna()) # 会删除有缺失值的那一整行
print(df.dropna(how='any'))
print(df.dropna(how='all')) # 这一整行全是na才删除
print(df.dropna(thresh=2)) # 如果至少有n个值不是na，就保留
print(df.dropna(axis=1)) #剔除有na的那一整列
print(df.dropna(subset=[1])) #column=1的地方有缺失值就删掉，可以用来指定筛查某column

0    1
1    2
dtype: object
     0     1  2
0  1.0  <NA>  2
1  2.0     3  4
2  NaN  None  3
     0  1  2
1  2.0  3  4
     0  1  2
1  2.0  3  4
     0     1  2
0  1.0  <NA>  2
1  2.0     3  4
2  NaN  None  3
     0     1  2
0  1.0  <NA>  2
1  2.0     3  4
   2
0  2
1  4
2  3
     0  1  2
1  2.0  3  4

In [52]:
# 填充缺失值
df = pd.read_csv('data/student_scores .csv')
df
print(df.isna().sum())
print(df.fillna({'语文':40})) # 使用字典来填充，固定填充缺失值：df.fillna({'column':固定值})
print(df.fillna(df[['数学']].mean())) # 数学行用平均值来填充：df.fillna(df[['column']].mean()
# 关于[[]] 和 [] ,前者返回一个只有一列的dataframe，后者返回一个数，建议用[],同时选两个columns的时候再用[[]]
print(df.ffill()) # 用前面的值填充
print(df.bfill()) # 用后面的值填充

Unnamed: 0    0
姓名            0
班级            0
语文            2
数学            6
英语            3
选科            0
dtype: int64
    Unnamed: 0  姓名      班级    语文    数学    英语  选科
0            0  张伟  高一(3)班  90.0  94.0  59.0  文科
1            1  李娜  高一(3)班  81.0   NaN   NaN  理科
2            2  王强  高一(2)班  62.0   NaN  63.0  文科
3            3  刘洋  高一(2)班  99.0  81.0  64.0  文科
4            4  陈静  高一(3)班  40.0  81.0  72.0  理科
5            5  杨帆  高一(3)班  83.0  70.0  61.0  文科
6            6  赵磊  高一(3)班  96.0  80.0  62.0  文科
7            7  周敏  高一(1)班  96.0  56.0   NaN  文科
8            8  吴昊  高一(1)班  91.0  90.0  68.0  理科
9            9  徐婷  高一(2)班  93.0   NaN  64.0  理科
10          10  孙杰  高一(3)班  66.0   NaN  63.0  理科
11          11  马丽  高一(2)班  70.0  56.0  58.0  理科
12          12  朱峰  高一(3)班  62.0  85.0  78.0  理科
13          13  胡军  高一(2)班  94.0   NaN  97.0  文科
14          14  林芳  高一(2)班  56.0   NaN  80.0  文科
15          15  郭涛  高一(3)班  40.0  83.0   NaN  理科
    Unnamed: 0  姓名      班级    语文    数学    英语  选科
0            0  张伟  高一(3)班  90.0  94.0  59.0  文科
1            1  李娜  高一(3)班  81.0  77.6   NaN  理科
2            2  王强  高一(2)班  62.0  77.6  63.0  文科
3            3  刘洋  高一(2)班  99.0  81.0  64.0  文科
4            4  陈静  高一(3)班   NaN  81.0  72.0  理科
5            5  杨帆  高一(3)班  83.0  70.0  61.0  文科
6            6  赵磊  高一(3)班  96.0  80.0  62.0  文科
7            7  周敏  高一(1)班  96.0  56.0   NaN  文科
8            8  吴昊  高一(1)班  91.0  90.0  68.0  理科
9            9  徐婷  高一(2)班  93.0  77.6  64.0  理科
10          10  孙杰  高一(3)班  66.0  77.6  63.0  理科
11          11  马丽  高一(2)班  70.0  56.0  58.0  理科
12          12  朱峰  高一(3)班  62.0  85.0  78.0  理科
13          13  胡军  高一(2)班  94.0  77.6  97.0  文科
14          14  林芳  高一(2)班  56.0  77.6  80.0  文科
15          15  郭涛  高一(3)班   NaN  83.0   NaN  理科
    Unnamed: 0  姓名      班级    语文    数学    英语  选科
0            0  张伟  高一(3)班  90.0  94.0  59.0  文科
1            1  李娜  高一(3)班  81.0  94.0  59.0  理科
2            2  王强  高一(2)班  62.0  94.0  63.0  文科
3            3  刘洋  高一(2)班  99.0  81.0  64.0  文科
4            4  陈静  高一(3)班  99.0  81.0  72.0  理科
5            5  杨帆  高一(3)班  83.0  70.0  61.0  文科
6            6  赵磊  高一(3)班  96.0  80.0  62.0  文科
7            7  周敏  高一(1)班  96.0  56.0  62.0  文科
8            8  吴昊  高一(1)班  91.0  90.0  68.0  理科
9            9  徐婷  高一(2)班  93.0  90.0  64.0  理科
10          10  孙杰  高一(3)班  66.0  90.0  63.0  理科
11          11  马丽  高一(2)班  70.0  56.0  58.0  理科
12          12  朱峰  高一(3)班  62.0  85.0  78.0  理科
13          13  胡军  高一(2)班  94.0  85.0  97.0  文科
14          14  林芳  高一(2)班  56.0  85.0  80.0  文科
15          15  郭涛  高一(3)班  56.0  83.0  80.0  理科
    Unnamed: 0  姓名      班级    语文    数学    英语  选科
0            0  张伟  高一(3)班  90.0  94.0  59.0  文科
1            1  李娜  高一(3)班  81.0  81.0  63.0  理科
2            2  王强  高一(2)班  62.0  81.0  63.0  文科
3            3  刘洋  高一(2)班  99.0  81.0  64.0  文科
4            4  陈静  高一(3)班  83.0  81.0  72.0  理科
5            5  杨帆  高一(3)班  83.0  70.0  61.0  文科
6            6  赵磊  高一(3)班  96.0  80.0  62.0  文科
7            7  周敏  高一(1)班  96.0  56.0  68.0  文科
8            8  吴昊  高一(1)班  91.0  90.0  68.0  理科
9            9  徐婷  高一(2)班  93.0  56.0  64.0  理科
10          10  孙杰  高一(3)班  66.0  56.0  63.0  理科
11          11  马丽  高一(2)班  70.0  56.0  58.0  理科
12          12  朱峰  高一(3)班  62.0  85.0  78.0  理科
13          13  胡军  高一(2)班  94.0  83.0  97.0  文科
14          14  林芳  高一(2)班  56.0  83.0  80.0  文科
15          15  郭涛  高一(3)班   NaN  83.0   NaN  理科

In [56]:
# 处理重复数据
data = {
    "name":['alice','alice','bob','alice','jack','bob'],
    "age":[26,25,30,25,35,30],
    "city":['NY','NY','LA','NY','SF','LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [64]:
df.duplicated() # 一整条记录都相同，标记为重复
df.drop_duplicates() # 直接把重复的那一整条删掉
print(df.drop_duplicates(subset=['name']) )# 可以指定删除哪特定column有重复的那一条数据
df.drop_duplicates(subset=['name'], keep='last') # keep='last':保留最新的那一条数据

    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [74]:
# 数据类型的转换
df=pd.read_csv('data/employees .csv',encoding='gbk')
df.dtypes

工号        str
姓名        str
部门        str
职位        str
入职日期      str
月薪      int64
是否在职      str
dtype: object

In [77]:
df['月薪'] = df['月薪'].astype('int16') #优化数据：int64对于某些数据太大了，永远都用不完。可以换成范围小一点的
df.dtypes

工号        str
姓名        str
部门        str
职位        str
入职日期      str
月薪      int16
是否在职      str
dtype: object

In [80]:
df['是否在职'] = df['是否在职'].astype('category') # 对于只有几种状态的东西，可以用‘分类’的数据类型储存
df['是否在职']

0     离职
1     离职
2     在职
3     在职
4     离职
5     离职
6     在职
7     离职
8     在职
9     在职
10    在职
11    在职
12    离职
13    在职
14    离职
15    在职
16    在职
17    离职
18    离职
19    在职
20    离职
21    离职
22    离职
23    离职
24    离职
25    离职
26    离职
27    离职
28    在职
29    在职
30    离职
31    离职
32    离职
33    离职
34    离职
35    离职
36    在职
37    在职
38    在职
39    在职
40    离职
41    离职
42    离职
43    在职
44    在职
45    在职
46    在职
47    离职
48    在职
49    在职
Name: 是否在职, dtype: category
Categories (2, str): ['在职', '离职']

In [84]:
df['is_在职'] = df['是否在职'].map({'在职':True,'离职':False}) # 用map来映射，数据更简单
df['is_在职']

0     False
1     False
2      True
3      True
4     False
5     False
6      True
7     False
8      True
9      True
10     True
11     True
12    False
13     True
14    False
15     True
16     True
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36     True
37     True
38     True
39     True
40    False
41    False
42    False
43     True
44     True
45     True
46     True
47    False
48     True
49     True
Name: is_在职, dtype: category
Categories (2, bool): [True, False]

In [86]:
# 数据变形
data = {
    'ID':[1,2],
    'name':['alice','bob'],
    'math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
df
df.T # 最简单的变形：转置

             0    1
ID           1    2
name     alice  bob
math        90   85
English     88   92
Science     95   89

In [90]:
'''
ID name 科目
1 alice math 90
1 alice English 88
1 alice Science 90
'''
# 宽表转换成长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数') # 新建了一个表，id_vars=['不变的列'],var_name='新建的列’，value_name='值的名字'
df2.sort_values(['name'])

   ID   name       科目  分数
0   1  alice     math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     math  85
3   2    bob  English  92
5   2    bob  Science  89

In [91]:
# 长表转宽表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数') # index=['不变的列'],columns='用哪一列当列名',value：列里面的数据值

科目        English  Science  math
ID name
1  alice       88       95    90
2  bob         92       89    85

In [113]:
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
# 分列
df['name'].str.split(" ",expand=True)  # expand可以把它转换成df的表格样式
df [['first name','last name']] = df['name'].str.split(" ") # .str. :转成字符串了之后可以用很多处理字符串的方法
df = pd.read_csv('data/employees .csv',encoding='gbk')
#df[['年份','月','日']] = (
df[['year','month','date']] = df['入职日期'].str.split("/",expand=True)
df['year'] = df['year'].astype('int16') # 转换数据类型
df['month'] = df['month'].astype('int8')
df['date'] = df['date'].astype('int8')
df.info() # 输出一些表格信息

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   工号      50 non-null     str
 1   姓名      50 non-null     str
 2   部门      50 non-null     str
 3   职位      50 non-null     str
 4   入职日期    50 non-null     str
 5   月薪      50 non-null     int64
 6   是否在职    50 non-null     str
 7   year    50 non-null     int16
 8   month   50 non-null     int8
 9   date    50 non-null     int8
dtypes: int16(1), int64(1), int8(2), str(6)
memory usage: 3.1 KB

In [119]:
# 数据分箱 pd.cut(x,bins,labels): x-->df,series;bins-->区间;labels-->每个区间叫什么，数据类型为list
df = pd.read_csv('data/employees .csv',encoding='gbk')
df.head()
df1 = df.head(10)[['工号','月薪']]
df1

     工号     月薪
0  E001  10135
1  E002  25575
2  E003   9249
3  E004  20796
4  E005  19065
5  E006  16240
6  E007   8199
7  E008   9164
8  E009  27954
9  E010  34445

In [130]:
pd.cut(df1['月薪'],bins=3) # bins=n,分成n段区间
pd.cut(df1['月薪'],bins=3).value_counts()
pd.cut(df1['月薪'],bins=[0,10000,20000,30000,40000]).value_counts() # bins也可以传入list作为参数
df1['经济水平'] = pd.cut(df1['月薪'],bins=[0,10000,20000,30000,40000],labels=['poor','low','medium','high'])
df1

     工号     月薪    经济水平
0  E001  10135     low
1  E002  25575  medium
2  E003   9249    poor
3  E004  20796  medium
4  E005  19065     low
5  E006  16240     low
6  E007   8199    poor
7  E008   9164    poor
8  E009  27954  medium
9  E010  34445    high

In [132]:
# 等人数分箱
pd.qcut(df1['月薪'],3)
pd.qcut(df1['月薪'],3).value_counts()

月薪
(8198.999, 10135.0]    4
(10135.0, 20796.0]     3
(20796.0, 34445.0]     3
Name: count, dtype: int64

In [139]:
# df.rename()  df.set_index()  df.reset_index()
df = pd.DataFrame({
    'name':['jack','alice','tom','bob'],
    'age':[20,30,40,50],
    'gender':['female','male','female','male']
})
print(df.set_index(['name'])) # 储存到另外一个表中，原来的df没变
df

       age  gender
name
jack    20  female
alice   30    male
tom     40  female
bob     50    male

    name  age  gender
0   jack   20  female
1  alice   30    male
2    tom   40  female
3    bob   50    male

In [149]:
df.reset_index(inplace=True) #变回去
df.set_index(['name'],inplace=True) # inplace=True：直接替换原表
df.reset_index(inplace=True)
df

    name  age  gender
0   jack   20  female
1  alice   30    male
2    tom   40  female
3    bob   50    male

In [150]:
df.rename(columns={'age':'年龄','gender':'性别'}) #对列重命名
df.rename(index={0:4}) #改index

    name  age  gender
4   jack   20  female
1  alice   30    male
2    tom   40  female
3    bob   50    male

In [154]:
# 直接修改属性
df.index=[1,2,3,4]
df.columns=['name','age','gender']
df

    name  age  gender
1   jack   20  female
2  alice   30    male
3    tom   40  female
4    bob   50    male